ee_api_key: script/sen12flood-qiuyangchen-8fdb42008616.json
ee_service_account: earthi-ubuntu@sen12flood-qiuyangchen.iam.gserviceaccount.com
  
sample:
  sample_mode: 'STRATIFIED' # RANDOM
  sample_length: 24
  which_label: 'DW'
  s1_bands: ['VV', 'VH']
  s2_bands: ['B1', 'B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B8A', 'B9', 'B10', 'B11', 'B12']
  year: 2020

data_loader:
  name: MLFluvDataset
  label: auto  # hand
  train_paths: data/fold_data
  tune_paths: data/fold_data

data_preprocess:
  convert_to_tif: True
  move_data: True
  handle_nan_in_sentinel: False
  fluv_point_only: False
  remap_to_sedi: False

plot_setting:
  plot_data: True

model:
  encoder: resnet34
  loss_function: CrossEntropyLoss
  weights: inverse_log
  temperature: 1
  distill_lamda: 0
  freeze_encoder: False

trainer:
  log_num: 1001
  mode: train # train, val, test, tune
  window_size: 512
  epochs: 50
  in_channels: 15
  classes: 6
  device: cuda
  learning_rate: 0.0001
  batch_size: 8
  exp_folder: ./experiments




