data_loader:
  name: MLFluvDataset
  test_paths: /mnt/ceph_rbd/data/labelled_data/test_dataset
  train_paths: /mnt/ceph_rbd/data/fold_data
  which_label: ESRI
data_preprocess:
  convert_to_tif: false
  fluv_point_only: true
  handle_nan_in_sentinel: false
  move_data: true
  remap_to_sedi: false
ee_api_key: script/sen12flood-qiuyangchen-8fdb42008616.json
ee_service_account: earthi-ubuntu@sen12flood-qiuyangchen.iam.gserviceaccount.com
incremental_learning:
  distill_lamda: 0
  freeze_encoder: false
  temperature: 1
  tune_log_num: 0
  with_extra_urban: true
model:
  encoder: resnet34
  loss_function: CrossEntropyLoss
  weights: inverse_countQ   
plot_setting:
  plot_data: true
sample:
  s1_bands:
  - VV
  - VH
  s2_bands:
  - B1
  - B2
  - B3
  - B4
  - B5
  - B6
  - B7
  - B8
  - B8A
  - B9
  - B10
  - B11
  - B12
  sample_length: 6000
  sample_mode: STRATIFIED
  year: 2020
trainer:
  batch_size: 16
  classes: 6
  device: cuda
  epochs: 50
  exp_folder: /mnt/ceph_rbd/script/experiments
  in_channels: 15
  learning_rate: 0.0001
  log_num: 1004
  mode: train
  train_fold:
  - 0
  - 1
  - 2
  - 3
  valid_fold:
  - 4
  window_size: 512
